update descriptions
CONP-PCNO/conp-dats-editor pull request #12
Opened 2020-11-25 19:28 UTC by liamocn

Related issues:
#8 
https://github.com/CONP-PCNO/conp-portal/issues/370

2020-11-25 21:34 UTC, cmadjar requested changes
@liamocn One tiny change to match was is in https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md and the fact that all sentences end with a dot.

Question: do you have some automated way to update those based on the CONP_DATS_fields.md document? Will it be easy to sync it or does one have to do that manually every time that file changes?

2020-11-25 21:34 UTC, cmadjar commented on src/components/forms/ExtraPropertiesForm/ExtraPropertiesForm.jsx
>            tooltip='The sources this dataset is derived from'
```suggestion
          tooltip='The sources this dataset is derived from.'
```

2020-11-26 17:18 UTC, liamocn commented
@cmadjar It's not straight-forward to sync because of the format difference. The .md file is markdown (which can contain links and is not just plain text) whereas what's displayed in the editor is jsx.

2020-11-26 17:19 UTC, cmadjar approved these changes

2020-11-26 17:20 UTC, cmadjar commented
@liamocn thanks for the clarification. I can see how this could end up being an issue when things are not updated automatically. Hope there won't be too many updates needed...

2020-11-26 17:20 UTC, merged